### ISSUE TITLE
`workflows/release.yaml` is not working on `v0.1.37`

### ISSUE THREAD

**Issue by windyakin** [takutakahashi/oci-image-operator#46]
@takutakahashi 

The following workflow is not working at the 0.1.37 release.

- https://github.com/takutakahashi/oci-image-operator/actions/workflows/release.yaml

So there are no images with v0.1.37 tags.

- https://github.com/takutakahashi/oci-image-operator/pkgs/container/oci-image-operator%2Factor-base
- https://github.com/takutakahashi/oci-image-operator/pkgs/container/oci-image-operator%2Fmanager
- and so on...

We also need the release.yaml included in the Assets of the release.

- https://github.com/takutakahashi/oci-image-operator/releases/download/v0.1.36/release.yaml

**Comment by takutakahashi** [comment]
v0.1.38 released!
